baseURL: "https://ehablog.pages.dev/"
languageCode: "en-us"
title: "Ehab's blog"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Hello!"
  mainMenu: false

menu:
  main:
    - identifier: home
      name: "Home"
      url: "/"
      weight: 1
    - identifier: tags
      name: "Tags"
      url: "/tags/"
      weight: 2
    - identifier: search
      name: "Search"
      url: "/search/"
      weight: 3
    - identifier: rss
      name: "RSS"
      url: "/index.xml"
      weight: 4


outputs:
  home:
    - HTML
    - RSS
